# -*- coding: utf-8 -*-
"""Spatial_biology.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ore1PdKHZgcttD8pMbhyMJOmqCcJsjUR
"""

import numpy as np
import matplotlib.pyplot as plt
import tifffile as tiff
import math
import os
import csv

"""#Print basic image statistics

Number of cycles, number of total channels, dimensions, and per-channel summary (min, max, mean, std).
"""

# File paths
file_path = "/content/A3R1_reg1.tif"
output_dir = "codex_analysis_results"
os.makedirs(output_dir, exist_ok=True)

# Load image
image = tiff.imread(file_path)
cycles, channels_per_cycle, height, width = image.shape
total_channels = cycles * channels_per_cycle

# Global stats

print("Image Statistics")
print(f"Number of cycles: {cycles}")
print(f"Channels per cycle: {channels_per_cycle}")
print(f"Total channels: {total_channels}")
print(f"Image dimensions: {height} x {width}")
print(f"Data type: {image.dtype}")
print()

# Per channel statistics
stats = []
for c in range(cycles):
    for ch in range(channels_per_cycle):
        channel_data = image[c, ch, :, :]
        stats.append({
            "cycle": c,
            "channel": ch,
            "min": np.min(channel_data),
            "max": np.max(channel_data),
            "mean": np.mean(channel_data),
            "std": np.std(channel_data)
        })

# Save per-channel stats to CSV
import pandas as pd
stats_df = pd.DataFrame(stats)
stats_df.to_csv(os.path.join(output_dir, "per_channel_statistics.csv"), index=False)

print("\nPer-channel statistics saved as CSV.")

"""Plot intensity histograms for all channels

Create a grid of histograms showing pixel intensity distribution for each channel.
"""

fig, axes = plt.subplots(cycles, channels_per_cycle, figsize=(3*channels_per_cycle, 2.5*cycles))
axes = np.array(axes).reshape(cycles, channels_per_cycle)

for c in range(cycles):
    for ch in range(channels_per_cycle):
        ax = axes[c, ch]
        channel_data = image[c, ch, :, :].ravel()
        ax.hist(channel_data, bins=50, color='gray')
        ax.set_title(f"Cycle {c}, Ch {ch}", fontsize=8)
        ax.set_yticks([])

plt.tight_layout()
hist_png = os.path.join(output_dir, "intensity_histograms.png")
hist_pdf = os.path.join(output_dir, "intensity_histograms.pdf")
plt.savefig(hist_png, dpi=300)
plt.savefig(hist_pdf)
plt.close()
print(f"Histograms saved as:\n {hist_png}\n {hist_pdf}")

"""Detect blank or low-signal channels

Identify and list any channels with mean intensity below a defined threshold.
"""

mean_threshold = 100.0
low_signal_channels = []

for c in range(cycles):
    for ch in range(channels_per_cycle):
        channel_data = image[c, ch]
        ch_mean = channel_data.mean()
        if ch_mean < mean_threshold:
            low_signal_channels.append((c, ch, ch_mean))

# Print results
if low_signal_channels:
    print("\nLow-signal channels (mean < {:.2f}):".format(mean_threshold))
    for c, ch, m in low_signal_channels:
        print(f"  Cycle {c}, Channel {ch}: mean={m:.2f}")
else:
    print("\nNo channels detected below the mean threshold of {:.2f}".format(mean_threshold))

threshold = 100.0
low_signal_channels = [
    (s['cycle'], s['channel'], s['mean'])
    for s in stats if s['mean'] < threshold
]
low_signal_df = pd.DataFrame(low_signal_channels, columns=["Cycle", "Channel", "Mean_Intensity"])
low_signal_df.to_csv(os.path.join(output_dir, "low_signal_channels.csv"), index=False)
print(f"Low-signal channels saved to {os.path.join(output_dir, 'low_signal_channels.csv')}")

"""Visualize all channels in a grid

Display the full set of channels (from all cycles) in a square grid layout using matplotlib.

Each subplot should be titled with its cycle and channel index.
"""

flattened_images = [
    image[c, ch, :, :]
    for c in range(cycles)
    for ch in range(channels_per_cycle)
]
titles = [
    f"C{c} Ch{ch}"
    for c in range(cycles)
    for ch in range(channels_per_cycle)
]

grid_size = math.ceil(math.sqrt(total_channels))
fig, axes = plt.subplots(grid_size, grid_size, figsize=(15, 15))
axes = axes.flatten()

for idx, ax in enumerate(axes):
    if idx < total_channels:
        ax.imshow(flattened_images[idx], cmap='gray')
        ax.set_title(titles[idx], fontsize=8)
        ax.axis('off')
    else:
        ax.axis('off')

plt.tight_layout()
grid_png = os.path.join(output_dir, "channel_grid.png")
grid_pdf = os.path.join(output_dir, "channel_grid.pdf")
plt.savefig(grid_png, dpi=300)
plt.savefig(grid_pdf)
plt.close()
print(f"Channel grid saved as:\n {grid_png}\n {grid_pdf}")

from zipfile import ZipFile
import shutil

# Zip the folder
shutil.make_archive("codex_analysis_results", 'zip', "codex_analysis_results")

from google.colab import files
files.download("codex_analysis_results.zip")

image = tiff.imread(file=)
image.shape()

flattend = image[c, ch, :, :].ravel()

max_intensity= np.max(image[c, ch, :, :])